name: Test
on:
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    runs-on: ubuntu-18.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn
      - run: yarn lint
  build:
    runs-on: ubuntu-18.04
    needs: lint
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn
      - run: yarn build
  test:
    runs-on: ubuntu-18.04
    needs: build
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Run unit tests
        run: |
          yarn install
          yarn test
      - name: Post coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
